/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DiamondCutFacet__factory } from "./DiamondCutFacet__factory";
export { DiamondLoupeFacet__factory } from "./DiamondLoupeFacet__factory";
export { TestFacet__factory } from "./TestFacet__factory";
export { TestFacet2__factory } from "./TestFacet2__factory";
