/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DiamondOrderNFT__factory } from "./DiamondOrderNFT__factory";
export { IOrderSVG__factory } from "./IOrderSVG__factory";
