/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOrderSVG,
  IOrderSVGInterface,
} from "../../../../contracts/diamond/DiamondOrderNFT.sol/IOrderSVG";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_key",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "_orderbook",
        type: "address",
      },
      {
        internalType: "string",
        name: "_market",
        type: "string",
      },
      {
        internalType: "address",
        name: "_app",
        type: "address",
      },
    ],
    name: "get_svg",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IOrderSVG__factory {
  static readonly abi = _abi;
  static createInterface(): IOrderSVGInterface {
    return new Interface(_abi) as IOrderSVGInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IOrderSVG {
    return new Contract(address, _abi, runner) as unknown as IOrderSVG;
  }
}
