/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as diamondOrderNftSol from "./DiamondOrderNFT.sol";
export { AppDia__factory } from "./AppDia__factory";
export { AppDiaInit__factory } from "./AppDiaInit__factory";
