/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as diamondOrderNftSol from "./DiamondOrderNFT.sol";
export type { diamondOrderNftSol };
export type { AppDia } from "./AppDia";
export type { AppDiaInit } from "./AppDiaInit";
