/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DiamondCutFacet } from "./DiamondCutFacet";
export type { DiamondLoupeFacet } from "./DiamondLoupeFacet";
export type { TestFacet } from "./TestFacet";
export type { TestFacet2 } from "./TestFacet2";
