/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TestFacetInterface extends Interface {
  getFunction(
    nameOrSignature: "test1Func1" | "test1Func2" | "test1Func3"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "test1Func1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test1Func2",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "test1Func3",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "test1Func1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "test1Func2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "test1Func3", data: BytesLike): Result;
}

export interface TestFacet extends BaseContract {
  connect(runner?: ContractRunner | null): TestFacet;
  waitForDeployment(): Promise<this>;

  interface: TestFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  test1Func1: TypedContractMethod<[], [string], "view">;

  test1Func2: TypedContractMethod<[va: BigNumberish], [void], "nonpayable">;

  test1Func3: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "test1Func1"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "test1Func2"
  ): TypedContractMethod<[va: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "test1Func3"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
