/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TestFacet2Interface extends Interface {
  getFunction(
    nameOrSignature: "test2Func1" | "test2Func2" | "test2Func3"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "test2Func1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "test2Func2",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "test2Func3",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "test2Func1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "test2Func2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "test2Func3", data: BytesLike): Result;
}

export interface TestFacet2 extends BaseContract {
  connect(runner?: ContractRunner | null): TestFacet2;
  waitForDeployment(): Promise<this>;

  interface: TestFacet2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  test2Func1: TypedContractMethod<[], [string], "view">;

  test2Func2: TypedContractMethod<[va: BigNumberish], [void], "nonpayable">;

  test2Func3: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "test2Func1"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "test2Func2"
  ): TypedContractMethod<[va: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "test2Func3"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
